name: Auto-Revert on Failed Checks

on:
  workflow_run:
    workflows: Deploy to GitHub Pages #Replace with your CI workflow name
    types:
      - completed

jobs:
  revert-on-failure:
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Revert the last merge
        run: |
          git revert -m 1 HEAD
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
